### ISSUE TITLE
Sample State, Frontend Routes

### ISSUE THREAD

**Issue by TahjDev** [omarluq/ExpectoStayLonger#2]
## Frontend Routes
- Will the reviewFormComponent be rendered conditionally? I thought oyu could only leave a review if you've left there
- You said that you cannot edit reservations, but you have an EditReservationComponent?
- Shouldnt the ReservationIndexItemComponent be inside of ReservationIndexComponent because thats what would render it?
- Will there not be a show page route for a specific reservation?

## Sample State
- The formatting for the code is just a bit off with the the curly braces being outside of the other code

**Comment by omarluq** [comment]
Sample State
The formatting for the code is just a bit off with the the curly braces being outside of the other code! im aware of this and i tried to fix it so many times but i cant figure out how to fix it !

**Comment by omarluq** [comment]
Frontend Routes
Will the reviewFormComponent be rendered conditionally? I thought oyu could only leave a review if you've left there
You said that you cannot edit reservations, but you have an EditReservationComponent?
Shouldnt the ReservationIndexItemComponent be inside of ReservationIndexComponent because thats what would render it?
Will there not be a show page route for a specific reservation? 

completed all the above ^
